POST https://pmusielak2023.azurewebsites.net/api/PeopleFn?code=vuP9y4ciXiuf-CqWUvG5QmYuR4SirzvCWwzolVJMMdhXAzFuw1r2ww== HTTP/1.1
content-type: application/json

{
    "FirstName": "Jan",
    "LastName": "Nowak",
    "AddressId": 1
}

GET https://pmusielak2023.azurewebsites.net/api/PeopleFn?code=vuP9y4ciXiuf-CqWUvG5QmYuR4SirzvCWwzolVJMMdhXAzFuw1r2ww== HTTP/1.1
content-type: application/json

{}

DELETE https://pmusielak2023.azurewebsites.net/api/PeopleFn?code=vuP9y4ciXiuf-CqWUvG5QmYuR4SirzvCWwzolVJMMdhXAzFuw1r2ww== HTTP/1.1
content-type: application/json

{
    "Id": 1
}

PUT https://pmusielak2023.azurewebsites.net/api/PeopleFn?code=vuP9y4ciXiuf-CqWUvG5QmYuR4SirzvCWwzolVJMMdhXAzFuw1r2ww== HTTP/1.1
content-type: application/json

{
    "Id": 1,
    "FirstName": "Kamil",
    "LastName": "Pawlak"
}

POST https://pmusielak2023.azurewebsites.net/api/AddressesFn?code=zjl_CbV1GR2POS1t7d8F1zenwkKwXdS3Vpf_RerwrYY_AzFut-7CXw== HTTP/1.1

{
    "City": "Poz",
    "AddressLine": "Kijowa"
}

GET https://pmusielak2023.azurewebsites.net/api/AddressesFn?code=zjl_CbV1GR2POS1t7d8F1zenwkKwXdS3Vpf_RerwrYY_AzFut-7CXw== HTTP/1.1
content-type: application/json

{}